### ISSUE TITLE
Fast-RTPS-Gen build problems.

### ISSUE THREAD

**Issue by AndyBlightLeeds** [eProsima/Fast-RTPS-Gen#37]
I have tried to build `fast-rtps-gen` v1.0.4 and had the same problem reported in #31.  The instructions at <https://dev.px4.io/master/en/setup/fast-rtps-installation.html#fast-rtps-gen> state:

```bash
git clone --recursive https://github.com/eProsima/Fast-RTPS-Gen.git -b v1.0.4 ~/Fast-RTPS-Gen \
    && cd ~/Fast-RTPS-Gen \
    && gradle assemble \
    && gradle install
```

After reading #31, I used the following:

```bash
git clone --recursive https://github.com/eProsima/Fast-RTPS-Gen.git -b v1.0.4 ~/Fast-RTPS-Gen \
    && cd ~/Fast-RTPS-Gen \
    && ./gradlew assemble \
    && ./gradlew install
```

This built OK but failed to install:

```bash
BUILD SUCCESSFUL in 25s
6 actionable tasks: 6 executed
> Task :install FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/andy/git/fast-rtps/Fast-RTPS-Gen/build.gradle' line: 58

* What went wrong:
Execution failed for task ':install'.
> Could not copy file '/home/andy/git/fast-rtps/Fast-RTPS-Gen/scripts/fastrtpsgen' to '/usr/local/bin/fastrtpsgen'.
   > /usr/local/bin/fastrtpsgen (Permission denied)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 535ms
1 actionable task: 1 executed
```
As I need to get something working quickly, I updated my script to manually copy the files I think I need:
```bash
    cd ${FAST_RTPS_GEN_DIR}
    ./gradlew assemble
    # ./gradlew install
    sudo mkdir -p /usr/local/share/fastrtps/
    sudo cp -f ./share/fastrtpsgen/java/fastrtpsgen.jar /usr/local/share/fastrtps/
    sudo cp -f scripts/fastrtpsgen /usr/local/bin/
```

Please fix the problem with the installation and then update the instructions to use the `./gradlew` command.

**Comment by TSC21** [comment]
@AndyBlightLeeds this is not an issue related to Fast-RTPS-Gen repo. Please close it. There is no problem to fix here.

Regarding the install: you can rather use gradlew or on the install process use `sudo env "PATH=$PATH" gradle install`, since it seems you don't have gradle with sudo permissions.

**Comment by AndyBlightLeeds** [comment]
Thanks for looking at this problem.  I used the following line to do the install and it works.
```bash
sudo env "PATH=$PATH" ./gradlew install
```
I'll create a pull request on the doc repo to correct the installation instructions.

**Comment by Tumb1eweed** [comment]
> ```shell
> sudo mkdir -p /usr/local/share/fastrtps/
> ```

use "./gradlew assemble" by java11, gets:
Downloading https://services.gradle.org/distributions/gradle-6.4-bin.zip

Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
        at org.gradle.wrapper.Download.download(Download.java:52)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
